version: "3.8"
services:
  audiveris:
    build:
      context: .
      dockerfile: Dockerfile.audiveris
    volumes:
      - ./input:/input
      - ./output:/output
    container_name: audiveris
    ports:
      - "5000:5000" # Opcjonalnie expose portu, jeśli Audiveris ma REST API

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/input
      - ./output:/output
    ports:
      - "8000:80"
    container_name: fastapi
